version: '3.7'

services:

  react-challenge-dev:
    container_name: react-challenge-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GITHUB_TOKEN=${REACT_APP_GITHUB_TOKEN}
